# Generated by Django 2.1 on 2020-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.TextField(max_length=200)),
                ('director_name', models.TextField(max_length=200)),
                ('movie_title', models.TextField(max_length=200)),
            ],
        ),
    ]
